import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import quran from '../quran.json';

import Verse from './verse'
import SearchBar from './searchBar';
const inter = Inter({ subsets: ['latin'] })
console.log(typeof quran);

export default function Home() {
  return (
    <>
      <Head>
        <title>وقفات</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <SearchBar />
          <Verse text="ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَـٰلَمِینَ ۝٢"/>
        </div>

      </main>
    </>
  )
}
